#!/usr/bin/env bash
set -euo pipefail

FREECAD_DIR="$HOME/.FreeCAD"
APPIMAGE_PATH="$FREECAD_DIR/FreeCAD.AppImage"
EXTRACT_DIR="$FREECAD_DIR/squashfs-root"

echo "==> Setting up FreeCAD headless environment..."

# --- Dependencies ---
echo "==> Installing system dependencies..."
sudo apt-get update -qq
sudo apt-get install -y --no-install-recommends \
    python3-pip \
    python3-dev \
    libfuse2 \
    wget \
    ca-certificates \
    libgl1 \
    libglib2.0-0 \
    libxcb1 \
    > /dev/null 2>&1

echo "==> Installing Python packages..."
pip3 install --quiet numpy

# --- Download FreeCAD AppImage ---
mkdir -p "$FREECAD_DIR"

if [ ! -f "$APPIMAGE_PATH" ]; then
    echo "==> Fetching latest FreeCAD release info..."

    # Resolve the latest release that has a Linux x86_64 AppImage
    RELEASE_JSON=$(wget -qO- "https://api.github.com/repos/FreeCAD/FreeCAD/releases" \
        --header="Accept: application/vnd.github+json")

    # Find the first AppImage asset URL across releases
    APPIMAGE_URL=$(echo "$RELEASE_JSON" | python3 -c "
import sys, json
releases = json.load(sys.stdin)
for release in releases:
    for asset in release.get('assets', []):
        name = asset['name']
        # Must be Linux x86_64 AppImage (not ARM, not conda, not source)
        if (name.endswith('.AppImage')
                and 'x86_64' in name
                and 'conda' not in name.lower()
                and 'aarch' not in name.lower()):
            print(asset['browser_download_url'])
            sys.exit(0)
print('NOT_FOUND')
")

    if [ "$APPIMAGE_URL" = "NOT_FOUND" ] || [ -z "$APPIMAGE_URL" ]; then
        echo "ERROR: Could not find a FreeCAD Linux x86_64 AppImage in recent releases."
        echo "       Check https://github.com/FreeCAD/FreeCAD/releases and set APPIMAGE_URL manually."
        exit 1
    fi

    echo "==> Downloading FreeCAD AppImage from:"
    echo "    $APPIMAGE_URL"
    wget -q --show-progress -O "$APPIMAGE_PATH" "$APPIMAGE_URL"
    chmod +x "$APPIMAGE_PATH"
else
    echo "==> FreeCAD AppImage already present, skipping download."
fi

# --- Extract AppImage ---
if [ ! -d "$EXTRACT_DIR" ]; then
    echo "==> Extracting AppImage (this may take a minute)..."
    cd "$FREECAD_DIR"
    "$APPIMAGE_PATH" --appimage-extract > /dev/null 2>&1
    echo "==> Extraction complete."
else
    echo "==> AppImage already extracted, skipping."
fi

# --- Locate the FreeCAD Python lib directory ---
# The extraction produces squashfs-root/usr/lib/ which contains FreeCAD.so (or FreeCAD*.so)
LIB_DIR="$EXTRACT_DIR/usr/lib"

if [ ! -d "$LIB_DIR" ]; then
    echo "ERROR: Expected lib directory not found at: $LIB_DIR"
    echo "       Contents of $EXTRACT_DIR:"
    ls "$EXTRACT_DIR" 2>/dev/null || true
    exit 1
fi

# Verify FreeCAD shared library is actually there
FREECAD_SO=$(find "$LIB_DIR" -maxdepth 1 -name "FreeCAD*.so" -o -name "FreeCAD.so" 2>/dev/null | head -1)
if [ -z "$FREECAD_SO" ]; then
    echo "ERROR: FreeCAD.so not found inside $LIB_DIR"
    echo "       Directory contents:"
    ls "$LIB_DIR" | head -30
    exit 1
fi

echo "==> Found FreeCAD library: $FREECAD_SO"

# --- Write .pth file so 'import FreeCAD' works from any python3 call ---
SITE_PACKAGES=$(python3 -c "import site; print(site.getsitepackages()[0])")
PTH_FILE="$SITE_PACKAGES/freecad-appimage.pth"

echo "==> Writing Python path config to: $PTH_FILE"
sudo tee "$PTH_FILE" > /dev/null <<EOF
# Auto-generated by ai-freecad setup.sh — points python3 at the extracted FreeCAD AppImage libs
$LIB_DIR
$EXTRACT_DIR/usr/Mod
EOF

# Some FreeCAD builds also need the Ext folder on sys.path
EXT_DIR="$EXTRACT_DIR/usr/Ext"
if [ -d "$EXT_DIR" ]; then
    echo "$EXT_DIR" | sudo tee -a "$PTH_FILE" > /dev/null
fi

# --- Verify import works ---
echo "==> Verifying 'import FreeCAD' works..."
if python3 -c "import FreeCAD; print('  FreeCAD version:', FreeCAD.Version())"; then
    echo ""
    echo "=========================================="
    echo " Setup complete! FreeCAD is importable."
    echo " Run scripts with: python3 scripts/hello_geometry.py"
    echo " FreeCADCmd binary: $EXTRACT_DIR/usr/bin/FreeCADCmd"
    echo "=========================================="
else
    echo ""
    echo "ERROR: 'import FreeCAD' failed after setup."
    echo "       .pth file written to: $PTH_FILE"
    echo "       lib dir used: $LIB_DIR"
    echo "       Check the above for missing .so files."
    exit 1
fi
